apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-nats
  labels:
    app: kube-nats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-nats
  template:
    metadata:
      labels:
        app: kube-nats
    spec:
      serviceAccountName: kube-nats
      containers:
      - name: kube-nats
        image: natsflow/kube-nats
        env:
        - name: "NATS_URL"
          value: "nats://nats-cluster:4222"
        - name: "CLUSTER"
          value: "minikube"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-nats-events
  labels:
    app: kube-nats-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-nats-events
  template:
    metadata:
      labels:
        app: kube-nats-events
    spec:
      serviceAccountName: kube-nats
      containers:
        - name: kube-nats
          image: natsflow/kube-nats
          env:
            - name: "NATS_URL"
              value: "nats://nats-cluster:4222"
            - name: "CLUSTER"
              value: "minikube"
            - name: "PUBLISH_EVENTS"
              value: "true"